BEGIN TRY
	EXEC spDataRange '2015-12-1', '2015-12-31';
END TRY 
BEGIN CATCH 
	PRINT 'ERROR NUMBER: ' + CONVERT(varchar(50), ERROR_NUMBER());
	PRINT 'ERROR MESSAGE: ' + CONVERT(varchar(50), ERROR_MESSAGE());
END CATCH;


BEGIN TRY
	EXEC spDataRange @DataMin = '2015-12-10';
END TRY 
BEGIN CATCH 
	PRINT 'ERROR NUMBER: ' + CONVERT(varchar(50), ERROR_NUMBER());
	PRINT 'ERROR MESSAGE: ' + CONVERT(varchar(50), ERROR_MESSAGE());
END CATCH;